WARNING    - 2024-06-08 23:16:57,949 - client          : PyNaCl is not installed, voice will NOT be supported
INFO       - 2024-06-08 23:16:57,953 - client          : logging in using static token
INFO       - 2024-06-08 23:16:58,586 - gateway         : Shard ID None has connected to Gateway (Session ID: a69cf9bb93808dabfdbf9113470c7b2c).
ERROR      - 2024-06-08 23:17:12,723 - bot             : Ignoring exception in command salmon
Traceback (most recent call last):
  File "c:\Users\josep\Documents\GitHub\discordbot\.venv\Lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\josep\Documents\GitHub\discordbot\splatink\rotationcmds.py", line 67, in salmon
    image_map = image_manipulation.make_salmon(rotations)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\josep\Documents\GitHub\discordbot\splatink\image_manipulation.py", line 96, in make_salmon
    weapon_img = Image.open(weapons + weaponmatcher.weapon_mapping[weapon])
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'Random'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\josep\Documents\GitHub\discordbot\.venv\Lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "c:\Users\josep\Documents\GitHub\discordbot\.venv\Lib\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\josep\Documents\GitHub\discordbot\.venv\Lib\site-packages\discord\ext\commands\core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'Random'
